AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  EndlessProjects

  Sample SAM Template for EndlessProjects

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  StockCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: endless-projects-stock-checker-function
      Handler: com.endless.projects.stock.checker.lambda.StockCheckerFunction::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /trigger
            Method: get
#      Layers:
#        - !Ref SeleniumDepLayer

#  SeleniumDepLayer:
#    Type: AWS::Serverless::LayerVersion
#    Properties:
#        LayerName: selenium-layer-dependencies
#        Description: Dependencies for headless chromedriver
#        ContentUri: selenium/
#        CompatibleRuntimes:
#          - java11

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  StockCheckerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt StockCheckerFunction.Arn
  StockCheckerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt StockCheckerFunctionRole.Arn
